import React, { useState } from "react";
import Head from "next/head";
const Navbar = ({ children }) => {
  const [isOpen, setIsOpen] = useState(false);

  const toggleSidebar = () => {
    setIsOpen(!isOpen);
  };
  const myFunction = () => {
    var x = document.getElementById("myTopnav");
    if (x.className === "topnav") {
      x.className += " responsive";
    } else {
      x.className = "topnav";
    }
  };
  return (
    <div>
      <Head>
        <title>Vlog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="topnav" id="myTopnav">
          <a href="/" className="active">หน้าแรก</a>
          <a href="touristattraction">แหล่งท่องเที่ยว</a>
          <a href="aboutme">เกี่ยวกับเรา</a>
          <a href="shop">ร้านค้า</a>
        </div>
      </div>
      {children}
    </div>
  );
};

export default Navbar;
